/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { WalletAccount } from './types';

export const INITIAL_WALLETS: WalletAccount[] = [
  {
    id: "WLT-VODA-01",
    provider: "Vodafone Cash",
    phone_or_account: "01002345678",
    owner_name: "OnTarget Liquid Merchant Hub A",
    label: "Main Retail Pay-In Pool",
    merchant_assignment: "all",
    daily_limit: 50000,
    used_today: 1250,
    priority: 8,
    active: true,
    minimum_amount: 10,
    maximum_amount: 15000,
    processor_name: "Vodafone Cash Gateway",
    merchant: "OnTarget Hub",
    retailer: "Vodafone Egypt Partner",
    site: "Primary Online Checkout",
    currency: "EGP",
    cost_type: "percentage",
    cost_percentage: 1.0,
    fixed_fee: 0,
    min_cost: 1,
    max_cost: 150,
    monthly_limit: 1500000,
  },
  {
    id: "WLT-INSTA-01",
    provider: "InstaPay",
    phone_or_account: "ontarget@instapay",
    owner_name: "OnTarget Corporate Liquidity Ltd",
    label: "High-Volume Realtime Instant Node",
    merchant_assignment: "all",
    daily_limit: 100000,
    used_today: 25400,
    priority: 10,
    active: true,
    minimum_amount: 100,
    maximum_amount: 50000,
    processor_name: "InstaPay national switch",
    merchant: "OnTarget LLC",
    retailer: "National Bank of Egypt",
    site: "B2B Cashier API",
    currency: "EGP",
    cost_type: "fixed",
    cost_percentage: 0,
    fixed_fee: 5,
    min_cost: 5,
    max_cost: 5,
    monthly_limit: 3000000,
  },
  {
    id: "WLT-BANK-CIB",
    provider: "Bank Transfer",
    phone_or_account: "EG12002200330044005500661",
    owner_name: "OnTarget Gateways For Trade",
    label: "CIB Premium Corporate Account",
    merchant_assignment: "all",
    daily_limit: 500000,
    used_today: 0,
    priority: 9,
    active: true,
    minimum_amount: 1000,
    maximum_amount: 250000,
    processor_name: "CIB Corporate Gateway",
    merchant: "OnTarget Gateways For Trade",
    retailer: "Commercial International Bank",
    site: "HQ Wire Portal",
    currency: "EGP",
    cost_type: "fixed",
    cost_percentage: 0,
    fixed_fee: 15,
    min_cost: 15,
    max_cost: 150,
    monthly_limit: 15000000,
  },
  {
    id: "WLT-VODA-02",
    provider: "Vodafone Cash",
    phone_or_account: "01088776655",
    owner_name: "Sherif Aly (Assigned Agent)",
    label: "Fallback Vodafone Channel 2",
    merchant_assignment: "Luxury Watch Co.",
    daily_limit: 30000,
    used_today: 0,
    priority: 5,
    active: true,
    minimum_amount: 10,
    maximum_amount: 15000,
    processor_name: "Vodafone Cash Gateway",
    merchant: "Luxury Watch Co.",
    retailer: "Kashier Agent network",
    site: "Luxury Boutique check",
    currency: "EGP",
    cost_type: "percentage",
    cost_percentage: 1.2,
    fixed_fee: 0,
    min_cost: 1,
    max_cost: 180,
    monthly_limit: 900000,
  },
  {
    id: "WLT-ORAN-01",
    provider: "Orange Cash",
    phone_or_account: "01211223344",
    owner_name: "OnTarget Orange Wallet B2B",
    label: "Orange Cash Secondary Pool",
    merchant_assignment: "all",
    daily_limit: 45000,
    used_today: 0,
    priority: 6,
    active: true,
    minimum_amount: 10,
    maximum_amount: 15000,
    processor_name: "Orange Cash link",
    merchant: "OnTarget Orange Wallet B2B",
    retailer: "Orange Egypt Gateway",
    site: "Orange Pay API",
    currency: "EGP",
    cost_type: "percentage",
    cost_percentage: 1.0,
    fixed_fee: 0,
    min_cost: 1,
    max_cost: 150,
    monthly_limit: 1350000,
  },
  {
    id: "WLT-ETIS-01",
    provider: "Etisalat Cash",
    phone_or_account: "01133445566",
    owner_name: "OnTarget Payment Gateways LLC",
    label: "Etisalat Cash Enterprise Main",
    merchant_assignment: "all",
    daily_limit: 45000,
    used_today: 0,
    priority: 7,
    active: true,
    minimum_amount: 10,
    maximum_amount: 15000,
    processor_name: "Etisalat Mashrou3 Gateway",
    merchant: "OnTarget Gateways LLC",
    retailer: "Etisalat Egypt Cash",
    site: "Etisalat Merchant Desk",
    currency: "EGP",
    cost_type: "percentage",
    cost_percentage: 1.1,
    fixed_fee: 0,
    min_cost: 1,
    max_cost: 165,
    monthly_limit: 1350000,
  },
  {
    id: "WLT-USDT-01",
    provider: "USDT",
    phone_or_account: "TYC7sBvYm9P6GgD1t4XnQrZ5qM1vYp3GzS",
    owner_name: "OnTarget Crypto Liquidity Node TRC20",
    label: "TRC20 USDT Settlement Tunnel",
    merchant_assignment: "all",
    daily_limit: 1000000,
    used_today: 43500,
    priority: 9,
    active: true,
    minimum_amount: 500,
    maximum_amount: 100000,
    processor_name: "Binance P2P & TRON network",
    merchant: "OnTarget Crypto Liquidity Node",
    retailer: "P2P Market Making",
    site: "Binance Merchant Portal",
    currency: "USDT",
    cost_type: "percentage",
    cost_percentage: 0.5,
    fixed_fee: 2.0,
    min_cost: 2.0,
    max_cost: 500,
    monthly_limit: 30000000,
  },
  {
    id: "WLT-WISE-01",
    provider: "Wise",
    phone_or_account: "treasury@ontarget-pay.com",
    owner_name: "OnTarget Pay Global Wise Treasury",
    label: "Wise EUR/USD Multi-currency Gateway",
    merchant_assignment: "all",
    daily_limit: 250000,
    used_today: 0,
    priority: 4,
    active: false,
    minimum_amount: 100,
    maximum_amount: 25000,
    processor_name: "Wise API Connector",
    merchant: "OnTarget Pay Global Wise Treasury",
    retailer: "Wise Business UK",
    site: "Wise Treasury Engine",
    currency: "USD",
    cost_type: "fixed",
    cost_percentage: 0.1,
    fixed_fee: 10,
    min_cost: 10,
    max_cost: 1000,
    monthly_limit: 7500000,
  }
];

export const AVAILABLE_CHANNELS = [
  "Vodafone Cash",
  "Orange Cash",
  "Etisalat Cash",
  "WE Pay",
  "InstaPay",
  "Bank Transfer",
  "Fawry",
  "Meeza",
  "PayPal",
  "Wise",
  "Revolut",
  "USDT"
];
